### ISSUE TITLE
Usage of fetch in shopifyApiProxy

### ISSUE THREAD

**Issue by felixjung** [Shopify/shopify-express#29]
Hey there,

I've been browsing through the code of this repo as we are looking to build something similar for our APIs at my current job. While browsing, I stumbled over [this|https://github.com/Shopify/shopify-express/blob/master/routes/shopifyApiProxy.js#L58].

```javascript
function fetchWithParams(url, fetchOpts, query) {
  const parsedUrl = new URL(url);

  Object.entries(query).forEach(([key, value]) => {
    parsedUrl.searchParams.append(key, value);
  });

  return fetch(parsedUrl.href, fetchOpts);
}
```

I can't find `fetch` being imported anywhere and it being a browser API, I would have thought this cannot work in node. Couldn't call `fetch` in the node REPL either. I'm just curious here, if you've found a way to do straight forward (i.e. no use of `http`) HTTP requests in node without third-party libraries.

Thanks for the great inspiration.

**Comment by TheMallen** [comment]
Thanks for opening this issue, the project was hastily pulled out of a folder in `shopify-node-app` so we've been dealing with the fallout of that bit by bit as we slowly move towards being out of alpha. Looks like we just didn't move over the fetch polyfill. If you want to use this code verbatim in your own project just `yarn add universal-fetch` and `require('universal-fetch')` anywhere in your code.

**Comment by felixjung** [comment]
OK cool, that's what I thought. Thanks.
