### ISSUE TITLE
Error getting accessToken

### ISSUE THREAD

**Issue by jasenguyen** [Shopify/shopify-express#33]
Hi, I wonder why the accessToken could be retrieved when running locally but Heroku. 
Here's what the error said:

> `GET /auth/shopify?shop=lskdfj.myshopify.com 304 2.288 ms - -
> 2017-12-13T15:57:27.999826+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'accessToken' of undefined
> 2017-12-13T15:57:27.999840+00:00 app[web.1]:     at shopStore.storeShop (/app/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
> 2017-12-13T15:57:27.999841+00:00 app[web.1]:     at MemoryStrategy.storeShop (/app/node_modules/@shopify/shopify-express/strategies/MemoryStrategy.js:13:12)
> 2017-12-13T15:57:27.999842+00:00 app[web.1]:     at fetch.then.then.responseBody (/app/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:84:19)
> 2017-12-13T15:57:27.999843+00:00 app[web.1]:     at <anonymous>
> 2017-12-13T15:57:27.999844+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:160:7)
> 2017-12-13T15:57:28.006774+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> 2017-12-13T15:57:28.006860+00:00 app[web.1]: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by TheMallen** [comment]
Does your app use express session? 

You need to have some sort of session middleware set up for this to work. See #21.

**Comment by jasenguyen** [comment]
@TheMallen thanks for your clear response. 
As deployed with Heroku, I think for now the best store strategy is to use its plugin such as Redis to Go. Then it works so fine.

**Comment by TheMallen** [comment]
NP :)

**Comment by TheMallen** [comment]
We're probably going to be adding a throw if no session middleware is hooked up or otherwise handle that case in a more user friendly way.
