### ISSUE TITLE
Incompatibility with AWS Lambda

### ISSUE THREAD

**Issue by jtyler258** [Shopify/shopify-express#35]
AWS Lambda is currently on node 6.10, and is a very good candidate for hosting shopify apps. However the oldest supported node version for shopify-express is 8.1. Are there plans to support 6 in the future? I guess I could always fork and try to babel back to 6.1

**Comment by jtyler258** [comment]
Just took a look at the code and there are only three spots that prevent it from running on 6.1
@shopify/shopify-express/index.js  Had to replace Object.assign
@shopify/shopify-express/routes/index.js Had to remove trailing comma
@shopify/shopify-express/routes/shopifyAuth.js Had to remove trailing comma

I changed these files to be 6.10 friendly and everything is working on lambda now.

Note: aws reeeally needs to keep lambda updated a bit better

**Comment by TheMallen** [comment]
We use async await in a few spots, which I think is only available in Node 7.6+. If you can get it working without changing that then I'd be open to accepting a PR and bumping down the minimum version.

**Comment by TheMallen** [comment]
I don't think we'll be cutting async / await, and I've confirmed that Lambda doesn't support it atm. 

AWS is supposed to update to 8+ sometime soon AFAIK, so hopefully they do.

I'm closing this for now.

**Comment by mikedizon** [comment]
Now that 8 is supported, should this work?
