### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by TheMallen** [Shopify/shopify-express#4]
As of right now the project has no tests to speak of. We should rectify this to facilitate faster iteration.

**Comment by AWaselnuk** [comment]
💯

**Comment by AWaselnuk** [comment]
We have now shipped some preliminary tests that demonstrate an approach to testing. This also allowed us to install the basic testing dependencies in the project. https://github.com/Shopify/shopify-express/pull/19

We now need to complete our test coverage and then we can close this issue.

**Comment by TheMallen** [comment]
Added tests in #31  as well :). Getting there.

**Comment by TheMallen** [comment]
Closing this in favour of specific issues.
