### ISSUE TITLE
withShop Middleware --- /install route paramaterization

### ISSUE THREAD

**Issue by Jtosbornex** [Shopify/shopify-express#80]
Forcing the base url of with shop to be /install is a bit of a burden. Imagine having multiple App credentials doing different but interrelated tasks on the same instance of a server.  Both requiring separate install routes. 

This is my case and it would be nice if 

`response.redirect('/install');`

could instead be 

`response.redirect('${authBaseUrl || baseUrl}/install');`

or something similar. Maybe even a new parameter instead of forcing /install

**Comment by janfabian** [comment]
It seems that pull request queue is not being processed, I created fork npm package `@topmonks/shopify-express` where this is working

``` javascript
app.get("/", withShop({ authBaseUrl: "/shopify", redirect: "/custom/install" }), (req, res) => {
  var { session: { shop, accessToken } } = req;
  return res.send("Home");
});
```
