### ISSUE TITLE
Error during build on Heroku

### ISSUE THREAD

**Issue by Werbelow** [Shopify/shopify-express#97]
The package works great on local env, however pushing to Heroku it breaks. 

```
remote:        [4/4] Building fresh packages...
remote:        error /tmp/build_ec62596718e2fd57917c6c2b077c5bc9/node_modules/sqlite3: Command failed.
remote:        Exit code: 1
remote:        Command: node-pre-gyp install --fallback-to-build
remote:        Arguments:
remote:        Directory: /tmp/build_ec62596718e2fd57917c6c2b077c5bc9/node_modules/sqlite3
remote:        Output:
remote:        node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
remote:        node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.7.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
remote:        node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
remote:        node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.7.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
```

I am not using any of the built-in strategies, and especially not the sqlite one, and yet it seems to be trying to download sqlite?

**Comment by janfabian** [comment]
Hi @Werbelow , do you use same node versions on your local machine and heroku ?

sqlite3 version 3 is not supported by node 10 and must be updated, there is already PR, but not merged..

**Comment by janfabian** [comment]
or use `@topmonks/shopify-express`, forked from this repo, maintained by me (I removed sqlite3 lib)

**Comment by Werbelow** [comment]
Hey @janfabian I just checked my node version on heroku and you are correct, it was not the same as my local env. Once I updated that, the build worked. 

Thanks!

**Comment by patrickbolle** [comment]
What node version are you on that works?

**Comment by Werbelow** [comment]
I am using version 8.9.1
